#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.14"
# dependencies = [
#     "pyyaml",
# ]
# ///
import pathlib, sys

sys.path.insert(0, str(pathlib.Path(__file__).parent / "src"))
from csb import main_entry

main_entry()
